[keyfile]
unmanaged-devices=

[connection]
# Forces new Wi-Fi connections to apply globally to all users.
# This causes NetworkManager to bypass KWallet and store the password directly.Document type abbreviation
permissions=