[General]
DisplayServer=wayland
InputMethod=qtvirtualkeyboard

[Wayland]
Enable=true
CompositorCommand=kwin_wayland --no-lockscreen
SessionDir=/usr/share/wayland-sessions

[Theme]
Current=breeze
CursorTheme=breeze_cursors

[General]
background=login-screen.png
