post_install() {
    # Quietly rebuild the icon cache (-f forces a rebuild and suppresses errors)
    if [ -d /usr/share/icons/Kader42 ]; then
        gtk-update-icon-cache -q -t -f /usr/share/icons/Kader42 2>/dev/null || true
    fi
}

post_upgrade() {
    post_install

    install -d "${pkgdir}/usr/share/plasma/look-and-feel/Kader42-Plasmatheme"
    install -d "${pkgdir}/usr/share/color-schemes"
    install -d "${pkgdir}/usr/share/wallpapers/Kader42-Wallpapers"

    rm -rf /usr/share/plasma/look-and-feel/Kader42
    rm -rf /usr/share/color-schemes/Kader42.colors
    rm -rf /usr/share/wallpapers/Kader42
}