
backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

pacman:
  num_retries: 0
  disable_download: false
  needed_only: false

operations:
  - install:
      - base
      - linux
      - linux-firmware
      - mkinitcpio
      - systemd
      - networkmanager
      - archlinux-keyring
      - sudo
      - openboard
      - alpm_octopi_utils-git
      - bluez
      - bluez-utils
      - bluez-deprecated-tools
      - bluez-obex
      - bluez-mesh
      - bluedevil
blueman