
backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

pacman:
  num_retries: 0
  disable_download: false
  needed_only: false

operations:
  - install:
      - base
      - linux
      - linux-firmware
      - mkinitcpio
      - sudo