# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the shell process job.
---
dontChroot: false
timeout: 10
verbose: false
script:
  - command: "systemctl enable NetworkManager"
    name: "Enable NetworkManager"
    name[nl]: "Activeer netwerkbeheerder"
    name[de]: "Aktiviere Netzwerkmanager"
  - command: "systemctl enable sddm"
    name: "Activate SDDM"
    name[de]: "Aktiviere SDDM"
    name[nl]: "SDDM activeren"
  - command: "systemctl enable cups"
    name: "Enable printer services"
    name[de]: "Aktiviere Druckerdienste"
    name[nl]: "Printerservices inschakelen"
  - command: "systemctl mask pacman-init"
    name: "Mask pacman-init"
    name[de]: "Maskiere pacman-init"
    name[nl]: "Maskeer pacman-init"

i18n:
  name: "System Service Configuration"
  name[de]: "Systemdienste konfigurieren"
  name[nl]: "Systeemdiensten configureren"
