---
type: shellprocess
interface: none
chroot: true
timeout: 30
script:
  - |
    nmcli -t -f DEVICE,TYPE,STATE device |
    grep ':ethernet:' |
    grep -v ':connected$' |
    cut -d: -f1 |
    while read dev; do
      nmcli device connect "$$dev" || true
    done
