dontChroot: false
timeout: 900

script: "bash /usr/bin/optional_packages_service.sh"

arguments:
    - ${google-chrome} | cut -c 1  
    - ${visual-studio-code-bin} | cut -c 1
    - ${heroic-games-launcher-bin} | cut -c 1
    - ${waydroid-git} | cut -c 1
    - ${waydroid-helper} | cut -c 1
    - ${waydroid-launcher-git} | cut -c 1
    - ${spotify} | cut -c 1

i18n:
  name: "Installation of optional packages"