---
qmlSearch: both
qmlFilename: notesqml

# Diese Label erscheinen in der linken Sidebar
label: "Licensing"
label[de]: "Lizenzhinweise"

# Diese Texte werden an die QML-Datei (config.notes) gesendet
notes: "Please accept the licenses."
notes[de]: "Durch die Auswahl von proprietärer Software wie Google Chrome, Visual Studio Code oder Spotify im nächsten Schritt erklären Sie sich mit den Lizenzbedingungen der jeweiligen Hersteller einverstanden. <br><br>Weitere Details finden Sie auf den jeweiligen Seiten der Hersteller:<br><a href='https://google.com/chrome/terms'>Google Chrome</a>"