---
units:
  - name: "NetworkManager.service"
    action: "enable"
  - name: "systemd-resolved.service"
    action: "enable"
  - name: "org.cups.cupsd.service"
    action: "enable"
  - name: "sddm.service"
    action: "enable"
  - name: "pacman-init.service"
    action: "mask"
  - name: "nm-firstboot-ethernet.service"
    action: "enable"
  - name: "flathub-init.service"
    action: "enable"
  - name: "iio-sensor-proxy.service"
    action: "enable"
  - name: "plymouth-killer.service"
    action: "enable"  
  - name: "delete-liveuser.service"
    action: "enable"
  - name: "calamares-uninstall.service"
    action: "enable"
  - name: "kader42-launcher-switcher@.service"
    action: "enable"