#!/bin/bash

export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"

# Am Anfang des Skripts den Modus speichern
DEBUG_ENABLED=false
if [[ "$1" == "debug" ]]; then
    DEBUG_ENABLED=true
fi

# Die Funktion nutzt dann die globale Variable
debugMessage() {
    if [ "$DEBUG_ENABLED" = true ]; then
        echo -e "\e[33m[DEBUG]\e[0m $1" # Mit ein bisschen Farbe (Gelb)
    fi
}

echo "[Kader42] Listening for tabletModeChanged..."
last_state=""

gdbus monitor --session \
  --dest org.kde.KWin \
  --object-path /org/kde/KWin |
while read -r line; do

    if [[ "$line" == *"tabletModeChanged"* ]]; then
        read -r nextline

        if [[ "$nextline" == *"true"* && "$last_state" != "1" ]]; then
            last_state="1"
            /usr/bin/plasma-convertible-switcher 1
        elif [[ "$nextline" == *"false"* && "$last_state" != "0" ]]; then
            last_state="0"
            /usr/bin/plasma-convertible-switcher 0
        fi
    fi
done