#!/bin/bash

export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"

echo "[Kader42 Tablet Event Listener] Sensor-based TabletMode started..."

LAST_MODE=""

   # Accelerometer orientation changed: right-up
  #  Tilt changed: face-down


monitor-sensor | while read -r line; do

    if echo "$line" | grep -q "Accelerometer orientation changed"; then
        
        if echo "$line" | grep -q "normal"; then
            MODE=0
        else
            MODE=1
        fi
        
    else
        continue
    fi

    # Debounce
    if [ "$MODE" != "$LAST_MODE" ]; then
        echo "[Kader42 Tablet Event Listener] Mode changed → $MODE"
        /usr/bin/kader42-plasma-convertible-switcher "$MODE"
        LAST_MODE="$MODE"
    fi

done
