post_install() {
    echo "[Kader42-Hooks] Enabling Kader⁴² hooks..."
    echo "[Kader42-Hooks] -> Drop-in configuration created in /etc/mkinitcpio.conf.d/."
    echo "[Kader42-Hooks] -> Regenerating Initramfs image..."
    mkinitcpio -P
}

post_upgrade() {
    post_install
}

post_remove() {
    echo "[Kader42-Hooks]: Disable Kader⁴² hooks"
    echo "[Kader42-Hooks]: -> Remove drop-in configuration."
    rm -rf /etc/mkinitcpio.conf.d/kader42-hooks.conf
    echo "[Kader42-Hooks]: -> Regenerate Initramfs image..."
    mkinitcpio -P
}