- type: command
  check: packagechooser_licenseq
  value: chrome
  command: "chroot /mnt /bin/bash -c 'sudo -u $CALAMARES_TARGET_USERNAME /usr/bin/yay -S --noconfirm google-chrome'"
- type: command
  check: packagechooser_licenseq
  value: vscode
  command: "chroot /mnt /bin/bash -c 'sudo -u $CALAMARES_TARGET_USERNAME /usr/bin/yay -S --noconfirm visual-studio-code-bin'"