---
# Einfaches UI-Modul mit Checkboxen
# (zuvor im settings.conf eingebunden als: pkgs)
type: "packagechooser"

packages:
  - name: "Google Chrome"
    description: "Schneller, sicherer Webbrowser (AUR: google-chrome)"
    icon: "/usr/share/icons/google_chrome.svg"
    selected: false
    package: "google-chrome"

  - name: "Visual Studio Code"
    description: "Quelltext-Editor und IDE (AUR: visual-studio-code-bin)"
    icon: "/usr/share/icons/vscode.svg"
    selected: false
    package: "visual-studio-code-bin"
