---
units:
  - name: "NetworkManager.service"
    action: "enable"
  - name: "systemd-resolved.service"
    action: "enable"
  - name: "cups"
    action: "enable"
  - name: "sddm.service"
    action: "enable"
  - name: "pacman-init.service"
    action: "mask"
  - name: "iio-sensor-proxy.service"
    action: "enable"
  - name: "kader42-cleanup.service"
    action: "enable"
  - name: "bluetooth.service"
    action: "enable"