i18n:
     name: "Copy kernel preferences..."
dontChroot: true  # WICHTIG: Muss auf dem Host laufen, um beide Pfade zu sehen
timeout: 30
script:
#     - command: "mkdir -p ${ROOT}/etc/mkinitcpio.d/"
    - command: "cp -R /etc/mkinitcpio.d/linux.preset ${ROOT}/etc/mkinitcpio.d/linux.preset"