# /etc/calamares/modules/shellprocess_fix_kernel.conf
---
dontChroot: false
timeout: 300
script:
  # Calamares sucht "scripts/fix_kernel.sh" relativ zum Konfigurations-Root.
  - command: "bash /usr/share/calamares/scripts/fix_kernel.sh" 
    name: "Execute Kernel Configuration and Pacman Fix Script"
    name[de]: "Führe Skript zur Kernel-Reparatur und Pacman-Fix aus"