[Journal]
# Limits the maximum amount of RAM used by the journal to 50 megabytes
SystemMaxUse=50M
# Deletes old logs immediately when free storage space runs low
KeepFree=200M
# Throttles log spam from individual services
RateLimitIntervalSec=30s
RateLimitBurst=100