title   Kader42 – Live System (Default)
sort-key 00
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
# FIRST, the microcodes (Important!)
initrd  /%INSTALL_DIR%/boot/intel-ucode.img
initrd  /%INSTALL_DIR%/boot/amd-ucode.img
# THEN the actual initramfs
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img

options archisobasedir=%INSTALL_DIR% archisolabel=kader42_mello loglevel=3 rd.systemd.show_status=false rd.udev.log_level=3 rd.udev.log_priority=3 vt.global_cursor_default=0 cow_spacesize=10G copytoram=n module_blacklist=pcspkr nvme_load=yes i915.enable_psr=0 intel_idle.max_cstate=4 intel_fastboot=1 i915.fastboot=1 systemd.show_status=false fsck.repair=yes fbcon=nodefer enable_fbc=1 console=tty2 consoleblank=1 i915.enable_psr=0