post_install() {
  echo "==> Activate Tray Icon live..."

  local active_user=$(who | awk '{print $1}' | head -n 1)

  if [ -n "$active_user" ]; then
      local user_uid=$(id -u "$active_user")
      
      # Die Befehle werden mit && sauber nacheinander im Kontext des Users ausgeführt
      SYSTEMD_BUS_VARIABLE=1 sudo -u "$active_user" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_uid/bus" \
        systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XAUTHORITY && \
      SYSTEMD_BUS_VARIABLE=1 sudo -u "$active_user" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_uid/bus" \
        systemctl --user daemon-reload && \
      SYSTEMD_BUS_VARIABLE=1 sudo -u "$active_user" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$user_uid/bus" \
        systemctl --user restart kader42-software-center-tray.service
  fi
}

post_upgrade() {
  post_install
}