post_install() {
  echo “==> [Kader⁴² software center] The Software Center tray icon has been registered for autostart.”
  echo “==> The icon will automatically appear in the system tray the next time you log in.”
  echo "---"
  echo "==> [Kader⁴² software center] Das Software Center Tray-Icon wurde für den Autostart registriert."
  echo "==> Das Icon wird beim nächsten Login automatisch im System-Tray angezeigt.
}

post_upgrade() {
  post_install
}