---
requirements:
    # Vorhandene Einträge...
    - name: /etc
      mode: "0o755"
    - name: /var/cache/pacman/pkg
      mode: "0o755"
    - name: /var/lib/pacman
      mode: "0o755"
      
    # NEUE, KRITISCHE EINTRÄGE HIERUNTER:
    - name: /etc/mkinitcpio.d # Das Verzeichnis, in dem die Hook-Konfigurationen liegen
      mode: "0o755"
    - name: /etc/initcpio
      mode: "0o755"

isRank: true

keyrings:
    - archlinux
    - manjaro