viewmode: "checkbox"
mode: optionalmultiple
method: dummy

items:
  - id: chrome
    #packages: [ chrome ]
    name: "Google Chrome"
    description: "The official web browser from Google."
    selected: false

  - id: vscode
    #packages: [ vscode ]
    name: "Visual Studio Code"
    description: "A powerful code editor."
    selected: false
