---
# Set to true to run in host, rather than target system
dontChroot: false

# Tune this for the commands you're actually running, or
# use the list-of-items form of commands to tune the timeout
# for each command individually.
timeout: 10

# This will copy the output from the command into the Calamares
# log file. No processing is done beyond log-each-line-separately,
# so this can introduce weirdness in the log if the script
# outputs e.g. escape codes.
#
# The default is `false`. This can also be set for each
# command individually.
verbose: true

timeout: 300
script:
  - command: "bash /usr/share/calamares/scripts/cleanup-temporary-files.sh" 
    name: "Execute Temporary Files Cleanup Script"
    name[de]: "Führe Skript zum Löschen temporärer Dateien aus"