---
type: shellprocess
dontChroot: false
timeout: 900

script: "bash /usr/bin/optional_packages_service.sh"

arguments:
    - ${google-chrome} | cut -c 1  
    - ${visual-studio-code-bin} | cut -c 1

i18n:
  name: "Installation of optional packages"