# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the shell process job.
---
dontChroot: false
timeout: 10
verbose: false
script:
  - command: "yay -Rns calamares-git --noconfirm"
    name: "Remove calamares installer"
    name[nl]: "Verwijder het Calamares-installatieprogramma"
    name[de]: "Entferne den Calamares Installer"
